### ISSUE TITLE
Segfaults with latest audio fixes

### ISSUE THREAD

**Issue by stefanberndtsson** [stefanberndtsson/ostis#22]
For some reason there are sporadic segfaults since the commit that introduced the audio output stuff (that doesn't work anyway). Regardless of turning audio on or not.

**Comment by larsbrinkhoff** [comment]
Instantaneous in my case.  Won't even boot to desktop.

**Comment by larsbrinkhoff** [comment]
Is it ok for `rasterpos` to be 5929632?

**Comment by stefanberndtsson** [comment]
Nope. `rasterpos` should not exceed 160256.

And as for instantaneousness, it seems to boot sometimes when trying repeatedly.

**Comment by larsbrinkhoff** [comment]
The `shifter_do_interrupts` HBL code calls `shifter_gen_picture` with an insane rasterpos.

**Comment by larsbrinkhoff** [comment]
Is it ok for `cpu->cycle` to be 12874944 at the very first call to `shifter_do_interrupts`?  `lastcpucnt` is 0.

**Comment by stefanberndtsson** [comment]
Something is probably overwritten and/or not initialised properly regarding cycles. There was a recent change with cycles from 32bit to 64bit as well.

**Comment by stefanberndtsson** [comment]
Yep, cpu->cycle wasn't initialised. Fixed now.
