### ISSUE TITLE
TOS text output

### ISSUE THREAD

**Issue by stefanberndtsson** [stefanberndtsson/ostis#34]
VDI seems to show white output for characters in some cases. Noticable when opening File info and trying to edit the filename.

**Comment by larsbrinkhoff** [comment]
Also, when viewing floppy contents as text, when a file is clicked and turns to reverse video, characters previously displayed may be dropped (black).

**Comment by stefanberndtsson** [comment]
This was due to a bug with LSR.L which is fixed now.
