### ISSUE TITLE
FDC issues and read track

### ISSUE THREAD

**Issue by stefanberndtsson** [stefanberndtsson/ostis#41]
There might be an issue around how register selection and data setting is done in the FDC. When booting, a read track request is sent now from TOS, which seems unlikely.

**Comment by larsbrinkhoff** [comment]
Also, there is an indication of a floppy error when switching from low to medium resolution in TOS 1.00.

**Comment by stefanberndtsson** [comment]
That's normal without a floppy (or a FAT-readable floppy at least) in the drive.

**Comment by stefanberndtsson** [comment]
FDC needs to be separated from the DMA parts, and DMA should be the one responsible for the memory mapping at ff8600

**Comment by stefanberndtsson** [comment]
Found http://www.info-coach.fr/atari/documents/_mydoc/FD-HD_Programming.pdf which describes quite a bit about the structure around the DMA/FDC/HDC.

**Comment by larsbrinkhoff** [comment]
Thank you @DrCoolzic!

**Comment by stefanberndtsson** [comment]
Ok, this bit is sort of mostly remade now, so closing this.

**Comment by DrCoolzic** [comment]
glad I could help :)
