### ISSUE TITLE
Keybaord and mouse input no longer works on OSX

### ISSUE THREAD

**Issue by lokedhs** [stefanberndtsson/ostis#62]
No input works. This problem was introduced in f803bc2d40aa20f57ef9a429dd03b43121c6d981

**Comment by larsbrinkhoff** [comment]
It seems strange, because all that *should* happen is that relative mouse reporting is enabled at reset.  This is the default according to [documentation](http://dbug.kicks-ass.net/dbugforums/cgi-bin/yabb2/YaBB.pl?num=1280676369).

Also, f803bc2 seems to be needed by Dungeon Master, because the only IKBD command it sends is a `RESET`.

**Comment by larsbrinkhoff** [comment]
We might try to improve diagnostics, and then try to run with `--loglevel IKBD:6,MFP0:6` to see what happens.  Or what doesn't happen.

**Comment by larsbrinkhoff** [comment]
Did you try many runs with and without f803bc2?  I believe something about the mouse isn't 100% reliable.  About once in ten runs, I get no mouse movement.

**Comment by larsbrinkhoff** [comment]
Whatever is done to fix the mouse problem.  Make sure to test with these applikations:

- GEM Desktop (standard configuration: relative mouse reporting)
- Dungeon Master (relative mouse reporting, defaults only)
- Spectrum 512 (absolute mouse reporting)
- Populous (absolute mouse reporting, single-character interrupt service routine)

**Comment by larsbrinkhoff** [comment]
@lokedhs Can you try this?  A few times.  https://github.com/larsbrinkhoff/ostis/tree/acia

**Comment by lokedhs** [comment]
With this branch it seems to work if the mouse is outside the window when starting, but fails when the pointer is inside the window.

**Comment by larsbrinkhoff** [comment]
@lokedhs I get that with `master` too.

**Comment by lokedhs** [comment]
Is there a simple solution?

**Comment by larsbrinkhoff** [comment]
@lokedhs I don't know!  I haven't looked into it.  At least it's good it's readily reproducible across Linux and OS X.

I'm guessing that the problem may be related to SDL sending a mouse event (almost?) immediately after starting the program.  This is then translated to an ACIA interrupt which the system isn't quite prepared to handle.

But that's just an unsupported guess.

**Comment by larsbrinkhoff** [comment]
Some investgation seems to confirm my guess.

Initially disabling the mouse, and only enabling it after `RESET` seems to do the trick.  That is now part of my `acia` branch.

**Comment by stefanberndtsson** [comment]
That acia branch is now merged, so this should no longer be an issue, right?

**Comment by lokedhs** [comment]
The mouse moves, but it moves completely erratically. When I move down-right the mouse sometimes moves in the correct direction, but mostly moves up-left, causing the pointer to mostly sit in the top-left corner of the screen.

I'm wondering if this is because of miscalculations with relative movement since I'm testing on such a slow machine. However, it used to work before.

**Comment by larsbrinkhoff** [comment]
Sorry to hear that.  In my tests everything seems fine.

@lokedhs, if you increase the log level for the IKBD, do you see overrun messages?

Maybe one could insert delays to simulate a slow machine, and see if that's a way to reproduce the problem.

**Comment by larsbrinkhoff** [comment]
@lokedhs This works now, right?

**Comment by lokedhs** [comment]
Yes, seems to work correctly now.
