### ISSUE TITLE
ostis won't compile under cygwin

### ISSUE THREAD

**Issue by ggnkua** [stefanberndtsson/ostis#99]
Currently building fails with the following errors:

lex expr.l
make[1]: lex: Command not found
Makefile:68: recipe for target 'expr.tab.c' failed
make[1]: *** [expr.tab.c] Error 127
make[1]: Leaving directory '/cygdrive/c/svn/ostis'
Makefile:48: recipe for target 'default' failed
make: *** [default] Error 2

This happens even after installing the proposed tools (flex, etc). When I changed LEX to flex in the makefile, compilation finished successfully. The attached patch fixes this for cygwin only.

[0001-Minor-fix-for-compiling-on-cygwin.zip](https://github.com/stefanberndtsson/ostis/files/184841/0001-Minor-fix-for-compiling-on-cygwin.zip)

**Comment by stefanberndtsson** [comment]
Thank you. Applied and pushed.

**Comment by larsbrinkhoff** [comment]
That's cool.  I used Cygwin extensively whenever I'm forced to use Windows.

Does SDL work well in Cygwin?  What framerate do you get?  (Press and release F12.)

**Comment by ggnkua** [comment]
Well I was contemplating opening an issue for this... :)

Currently I try to run ostis like this:

./ostis.exe  -t tos102uk.img

No windows open at all, the console is frozen, and the laptop's fans start spinning to warp speed! At this point I can only ctrl-c. I'm really not sure how to proceed with this, but if you guys don't use windows at all I wasn't sure I should bug you with this. For all we know it might be a known sdl2 bug on Windows.

**Comment by stefanberndtsson** [comment]
We don't generally use windows, but if you come up with solutions that can be properly merged/integrated, I'll definitely add them.

**Comment by ggnkua** [comment]
I'll have to politely decline! C, SDL and Windows programming (any combination of them or just any of them separately) are some of the things I try to avoid tackling in my spare time :)

**Comment by stefanberndtsson** [comment]
Understandable. You are welcome to contribute in the future, whatever platform you choose to use. :)
